name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.49.1

    steps:
      - name: Install Dependencies
        run: npm install

      - name: Give Permission
        run: chmod +x node_modules/.bin/playwright

      - name: Run Test
        run: npx playwright test
