name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository letöltése
        uses: actions/checkout@v4

      - name: Node.js telepítése
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Függőségek telepítése
        run: npm install

      - name: Playwright böngészők telepítése
        run: npx playwright install --with-deps

      - name: Tesztek futtatása
        run: npx playwright test
